apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  labels:
    app: notification-service-pod
spec:
  selector:
    matchLabels:
      app: notification-service-pod
  template:
    metadata:
      labels:
        app: notification-service-pod
    spec:
      containers:
      - name: notification-service
        image: kartavyanirwel/mini-mesh-notification-service:13
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8000