apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service-pod
spec:
  selector:
    app: notification-service-pod
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
